### PR TITLE
finished proof

### PR DESCRIPTION
**Pull request by benediktahrens**
i finished the proof of `key2': if a functor is pointwise the colimit, then it is the colimit.

### CODE REVIEW

**Comment by benediktahrens** [comment]
I have removed a `apply CC.' which did not work, in the middle of a proof, without understanding the context of what I am doing. So please take a look to see if I did something stupid.

**Comment by benediktahrens** [comment]
There should be a warning when applying the construction of right Kan extensions. I am thinking about implementing it as a dummy argument of type True, with having an alias, such as

```
Definition is_small (C : precategory) : UU := unit.
```

Having that as a dummy argument of the function that we should not have used would be good?
Other ideas?
@rmatthes ?

**Comment by mortberg** [comment]
Something like `is_small` would indeed be good.

**Comment by mortberg** [comment]
I moved the construction of right Kan extensions to the file on them now. I suggest we add a comment or a dummy argument as Benedikt suggest.

**Pull request merged**
